# Generated by Django 5.2.7 on 2025-10-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('salary', models.CharField(max_length=100)),
                ('contract', models.CharField(max_length=100)),
                ('icon', models.URLField(blank=True, null=True)),
                ('description', models.TextField()),
                ('responsibilities', models.TextField()),
                ('requirements', models.TextField()),
                ('benefits', models.TextField()),
                ('workplace_photos', models.TextField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job Posting',
                'verbose_name_plural': 'Job Postings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Green Tara', max_length=200)),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('hero_title', models.CharField(default='Connecting Kenyans to trusted job opportunities', max_length=500)),
                ('hero_subtitle', models.TextField(default='Browse verified listings locally and in Qatar')),
                ('about_text', models.TextField(default='Green Tara helps job seekers connect to verified opportunities')),
                ('contact_email', models.EmailField(default='info@greentara.co.ke', max_length=254)),
                ('contact_phone', models.CharField(default='+254 700 123 456', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Content',
                'verbose_name_plural': 'Site Content',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.IntegerField()),
                ('job_title', models.CharField(max_length=200)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('kcse_grade', models.CharField(max_length=10)),
                ('cv_document', models.FileField(blank=True, null=True, upload_to='applications/cv/')),
                ('id_document', models.FileField(blank=True, null=True, upload_to='applications/id/')),
                ('certificate_document', models.FileField(blank=True, null=True, upload_to='applications/certificates/')),
                ('additional_documents', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected')], default='pending', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Internal admin notes', null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job Application',
                'verbose_name_plural': 'Job Applications',
                'ordering': ['-applied_at'],
                'unique_together': {('job_id', 'email')},
            },
        ),
    ]
