# Generated by Django 5.2.7 on 2025-10-26 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='application',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='workplace_photos',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
